# Generated by Django 5.2.15 on 2026-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassessment',
            name='primary_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_control_assignments', to='webapp.membership'),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='supporting_owners',
            field=models.ManyToManyField(blank=True, related_name='supporting_control_assignments', to='webapp.membership'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='data_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='environment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='system',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='system',
            name='system_owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='system',
            name='system_owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
