# Generated by Django 5.2.15 on 2026-08-13 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_evidencerequest_evidenceartifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('weakness_description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('compensating_controls', models.TextField(blank=True)),
                ('closure_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('READY_VALIDATION', 'Ready for validation'), ('CLOSED', 'Closed'), ('RISK_ACCEPTED', 'Risk accepted')], default='OPEN', max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('likelihood', models.CharField(choices=[('RARE', 'Rare'), ('UNLIKELY', 'Unlikely'), ('POSSIBLE', 'Possible'), ('LIKELY', 'Likely'), ('ALMOST_CERTAIN', 'Almost certain')], default='POSSIBLE', max_length=20)),
                ('residual_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('date_identified', models.DateField()),
                ('planned_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('risk_acceptance_requested', models.BooleanField(default=False)),
                ('risk_acceptance_rationale', models.TextField(blank=True)),
                ('risk_acceptance_expires', models.DateField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('validation_notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='webapp.assessment')),
                ('closure_evidence', models.ManyToManyField(blank=True, related_name='remediation_plans', to='webapp.evidenceartifact')),
                ('controls', models.ManyToManyField(related_name='remediation_plans', to='webapp.controlassessment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_remediation_plans', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_remediation_plans', to='webapp.membership')),
                ('risk_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_remediation_risks', to='webapp.membership')),
                ('supporting_owners', models.ManyToManyField(blank=True, related_name='supported_remediation_plans', to='webapp.membership')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_remediation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', '-priority', 'planned_completion', 'remediation_id'),
            },
        ),
        migrations.CreateModel(
            name='RemediationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('BLOCKED', 'Blocked')], default='NOT_STARTED', max_length=15)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_milestones', to='webapp.membership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='webapp.remediationplan')),
            ],
            options={
                'ordering': ('sequence', 'due_date', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='remediationplan',
            constraint=models.UniqueConstraint(fields=('assessment', 'remediation_id'), name='unique_assessment_remediation_id'),
        ),
    ]
