# Generated by Django 5.2.15 on 2026-08-13 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remediationplan_remediationmilestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WORKBOOK', 'Assessment workbook'), ('SSP', 'Word Security Plan'), ('REMEDIATION', 'Remediation workbook'), ('PACKAGE', 'Complete assessment package')], max_length=15)),
                ('filename', models.CharField(max_length=300)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('readiness', models.JSONField(blank=True, default=dict)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='webapp.assessment')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_omni_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
    ]
