# Generated by Django 5.2.15 on 2026-08-13 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_assessments(apps, schema_editor):
    Framework = apps.get_model("webapp", "Framework")
    Assessment = apps.get_model("webapp", "Assessment")
    AssessmentFramework = apps.get_model("webapp", "AssessmentFramework")
    Framework.objects.filter(code="CMMC-L2").update(
        authority="U.S. Department of Defense",
        description="CMMC Level 2 assessment requirements aligned to NIST SP 800-171.",
        scoring_method="SPRS", maximum_score=110, active=True,
    )
    for assessment in Assessment.objects.all().iterator():
        AssessmentFramework.objects.get_or_create(
            assessment_id=assessment.id, framework_id=assessment.framework_id,
            defaults={"is_primary": True, "added_by_id": assessment.created_by_id},
        )


def reverse_existing_assessments(apps, schema_editor):
    apps.get_model("webapp", "AssessmentFramework").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_generateddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='framework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='maximum_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framework',
            name='scoring_method',
            field=models.CharField(choices=[('NONE', 'No numeric score'), ('SPRS', 'SPRS'), ('DEDUCTION', 'Maximum less deductions')], default='NONE', max_length=15),
        ),
        migrations.CreateModel(
            name='AssessmentFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_assessment_frameworks', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_selections', to='webapp.assessment')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_selections', to='webapp.framework')),
            ],
            options={
                'ordering': ('-is_primary', 'framework__name', 'framework__version'),
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='frameworks',
            field=models.ManyToManyField(related_name='multi_assessments', through='webapp.AssessmentFramework', to='webapp.framework'),
        ),
        migrations.RunPython(migrate_existing_assessments, reverse_existing_assessments),
        migrations.AddConstraint(
            model_name='assessmentframework',
            constraint=models.UniqueConstraint(fields=('assessment', 'framework'), name='unique_assessment_framework'),
        ),
        migrations.AddConstraint(
            model_name='assessmentframework',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('assessment',), name='one_primary_framework_per_assessment'),
        ),
    ]
