# Generated by Django 5.2.15 on 2026-08-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_framework_active_framework_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('EQUIVALENT', 'Equivalent'), ('PARTIAL', 'Partially equivalent'), ('RELATED', 'Related')], default='RELATED', max_length=15)),
                ('mapping_reference', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_mappings', to='webapp.requirement')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_mappings', to='webapp.requirement')),
            ],
            options={
                'ordering': ('source__framework__code', 'source__requirement_id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_requirement_mapping_direction'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='requirement_mapping_not_self')],
            },
        ),
    ]
