# Generated by Django 5.2.15 on 2026-08-13 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_requirementmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='engagement_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='engagement_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quality_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='quality_review_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('CHANGES_REQUIRED', 'Changes required')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sampling_methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scope_boundaries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_off_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssessmentObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('source_document', models.CharField(blank=True, max_length=250)),
                ('source_version', models.CharField(blank=True, max_length=50)),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='webapp.requirement')),
            ],
            options={
                'ordering': ('requirement__requirement_id', 'objective_id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('EXAMINE', 'Examine'), ('INTERVIEW', 'Interview'), ('TEST', 'Test'), ('OBSERVE', 'Observe')], max_length=12)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('assessment_object', models.TextField()),
                ('source_page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='webapp.assessmentobjective')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_procedures', to='webapp.requirement')),
            ],
            options={
                'ordering': ('method', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD', 'Lead assessor'), ('ASSESSOR', 'Assessor'), ('REVIEWER', 'Quality reviewer'), ('SME', 'Subject-matter expert')], max_length=12)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='webapp.assessment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_team_assignments', to='webapp.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MET', 'MET'), ('NOT_MET', 'NOT MET'), ('NOT_APPLICABLE', 'NOT APPLICABLE'), ('NOT_ASSESSED', 'NOT ASSESSED')], default='NOT_ASSESSED', max_length=20)),
                ('assessor_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessed_objectives', to=settings.AUTH_USER_MODEL)),
                ('control_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_results', to='webapp.controlassessment')),
                ('evidence', models.ManyToManyField(blank=True, related_name='objective_results', to='webapp.evidenceartifact')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='webapp.assessmentobjective')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('scheduled_at', models.DateTimeField()),
                ('location_or_link', models.CharField(blank=True, max_length=500)),
                ('participants', models.TextField(help_text='Names, titles, and organizational roles.')),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='webapp.assessment')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_interviews', to='webapp.membership')),
                ('objectives', models.ManyToManyField(blank=True, related_name='interviews', to='webapp.objectiveassessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('population_description', models.TextField()),
                ('population_size', models.PositiveIntegerField()),
                ('sample_size', models.PositiveIntegerField()),
                ('selection_method', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('selected_items', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='webapp.assessment')),
                ('objectives', models.ManyToManyField(blank=True, related_name='samples', to='webapp.objectiveassessment')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField()),
                ('steps_performed', models.TextField()),
                ('expected_result', models.TextField(blank=True)),
                ('actual_result', models.TextField()),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INCONCLUSIVE', 'Inconclusive')], max_length=15)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='webapp.assessment')),
                ('evidence', models.ManyToManyField(blank=True, related_name='test_executions', to='webapp.evidenceartifact')),
                ('objective_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='webapp.objectiveassessment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_executions', to='webapp.membership')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='webapp.assessmentprocedure')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentobjective',
            constraint=models.UniqueConstraint(fields=('requirement', 'objective_id'), name='unique_requirement_objective'),
        ),
        migrations.AddConstraint(
            model_name='assessmentprocedure',
            constraint=models.UniqueConstraint(fields=('requirement', 'objective', 'method', 'sequence'), name='unique_assessment_procedure'),
        ),
        migrations.AddConstraint(
            model_name='assessmentteammember',
            constraint=models.UniqueConstraint(fields=('assessment', 'membership'), name='unique_assessment_team_member'),
        ),
        migrations.AddConstraint(
            model_name='objectiveassessment',
            constraint=models.UniqueConstraint(fields=('control_result', 'objective'), name='unique_control_objective_result'),
        ),
    ]
