# Generated by Django 5.2.15 on 2026-08-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_evidencereviewhistory_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='notify_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remediationmilestone',
            name='notify_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remediationplan',
            name='notify_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('QUEUED', 'Queued for digest'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_REQUESTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='delivery',
            field=models.CharField(choices=[('IN_APP', 'In-app only'), ('EMAIL', 'In-app and immediate email'), ('DAILY', 'In-app and daily email digest'), ('WEEKLY', 'In-app and weekly email digest')], default='IN_APP', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('first_reminder_days', models.PositiveSmallIntegerField(default=7)),
                ('second_reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('notify_on_due_date', models.BooleanField(default=True)),
                ('overdue_escalation_days', models.PositiveSmallIntegerField(default=1)),
                ('repeat_overdue_days', models.PositiveSmallIntegerField(default=7)),
                ('escalation_recipients', models.CharField(choices=[('OWNER', 'Owner only'), ('LEAD', 'Owner and lead assessor'), ('CLIENT', 'Owner, lead assessor, and System Owner')], default='LEAD', max_length=10)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_policy', to='webapp.organization')),
            ],
        ),
    ]
