from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies = [("webapp", "0015_mapping_curation"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AddField(model_name="evidenceartifact", name="expires_on", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="evidenceartifact", name="superseded_by", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="supersedes", to="webapp.evidenceartifact")),
        migrations.AddField(model_name="evidencerequest", name="consolidated_into", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="consolidated_requests", to="webapp.evidencerequest")),
        migrations.CreateModel(name="EvidenceApplicability", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("applicability", models.CharField(choices=[("FULL", "Fully applicable"), ("PARTIAL", "Partially applicable"), ("NOT_APPLICABLE", "Not applicable"), ("ADDITIONAL_REQUIRED", "Additional evidence required")], max_length=25)), ("rationale", models.TextField(blank=True)), ("scope_limitations", models.TextField(blank=True)), ("reviewed_at", models.DateTimeField(auto_now=True)), ("artifact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applicability_reviews", to="webapp.evidenceartifact")), ("control_result", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_applicability", to="webapp.controlassessment")), ("reviewed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence_applicability_reviews", to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name="evidenceapplicability", constraint=models.UniqueConstraint(fields=("artifact", "control_result"), name="unique_evidence_applicability")),
        migrations.CreateModel(name="TestReuseReference", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("limitations", models.TextField(blank=True)), ("approved_at", models.DateTimeField(auto_now_add=True)), ("approved_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approved_test_reuse", to=settings.AUTH_USER_MODEL)), ("reuse_decision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="test_references", to="webapp.assessmentreusedecision")), ("source_test", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reuse_references", to="webapp.testexecution")), ("target_objective", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reused_tests", to="webapp.objectiveassessment"))]),
        migrations.AddConstraint(model_name="testreusereference", constraint=models.UniqueConstraint(fields=("source_test", "target_objective"), name="unique_test_reuse_target")),
    ]
