from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[("webapp","0017_multiframework_reporting"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.AddField(model_name="requirementmapping",name="lifecycle",field=models.CharField(choices=[("DRAFT","Draft"),("PENDING","Pending review"),("APPROVED","Approved"),("REJECTED","Rejected"),("SUPERSEDED","Superseded"),("RETIRED","Retired")],default="APPROVED",max_length=15)),migrations.AddField(model_name="requirementmapping",name="revision",field=models.PositiveIntegerField(default=1)),migrations.AddField(model_name="requirementmapping",name="effective_date",field=models.DateField(blank=True,null=True)),migrations.AddField(model_name="generateddocument",name="stale",field=models.BooleanField(default=False)),
  migrations.CreateModel(name="MappingChangeRequest",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("proposed_relationship",models.CharField(choices=[("EQUIVALENT","Equivalent"),("PARTIAL","Partially equivalent"),("RELATED","Related"),("SUPPORTS","Supports")],max_length=15)),("proposed_rationale",models.TextField()),("proposed_confidence",models.DecimalField(blank=True,decimal_places=3,max_digits=4,null=True)),("reason",models.TextField()),("status",models.CharField(choices=[("PENDING","Pending review"),("APPROVED","Approved"),("REJECTED","Rejected")],default="PENDING",max_length=10)),("requested_at",models.DateTimeField(auto_now_add=True)),("reviewed_at",models.DateTimeField(blank=True,null=True)),("reviewer_comment",models.TextField(blank=True)),("mapping",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="change_requests",to="webapp.requirementmapping")),("requested_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="mapping_changes_requested",to=settings.AUTH_USER_MODEL)),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="mapping_changes_reviewed",to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name="MappingHistory",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("revision",models.PositiveIntegerField()),("snapshot",models.JSONField()),("action",models.CharField(max_length=30)),("created_at",models.DateTimeField(auto_now_add=True)),("actor",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="mapping_history_events",to=settings.AUTH_USER_MODEL)),("mapping",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="history",to="webapp.requirementmapping"))]),
  migrations.CreateModel(name="RevalidationTask",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("reason",models.TextField()),("status",models.CharField(choices=[("OPEN","Open"),("CONFIRMED","Revalidated"),("NO_ACTION","No action required")],default="OPEN",max_length=12)),("created_at",models.DateTimeField(auto_now_add=True)),("assessment",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="revalidation_tasks",to="webapp.assessment")),("change_request",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="revalidation_tasks",to="webapp.mappingchangerequest")),("reuse_decision",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="revalidation_tasks",to="webapp.assessmentreusedecision"))])]
