# Generated by Django 5.2.15 on 2026-08-15 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_risk_treatment_monitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='prior_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_assessments', to='webapp.assessment'),
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope_boundaries', models.TextField(blank=True)),
                ('assessment_locations', models.TextField(blank=True)),
                ('sampling_methodology', models.TextField(blank=True)),
                ('evidence_request_blueprints', models.JSONField(blank=True, default=list)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('risk_management_enabled', models.BooleanField(default=False)),
                ('include_risk_in_reports', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('NONE', 'Not recurring'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUAL', 'Every six months'), ('ANNUAL', 'Annual')], default='NONE', max_length=12)),
                ('next_start_date', models.DateField(blank=True, null=True)),
                ('default_duration_days', models.PositiveSmallIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessment_templates', to=settings.AUTH_USER_MODEL)),
                ('created_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='webapp.assessment')),
                ('frameworks', models.ManyToManyField(related_name='assessment_templates', to='webapp.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='webapp.organization')),
                ('primary_framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_assessment_templates', to='webapp.framework')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='webapp.assessmenttemplate'),
        ),
        migrations.CreateModel(
            name='IntegrationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('IN_APP', 'In-app only'), ('EMAIL', 'Email'), ('EXTERNAL', 'External ticket'), ('BOTH', 'Email and external ticket')], default='IN_APP', max_length=12)),
                ('provider', models.CharField(choices=[('NONE', 'Not configured'), ('JIRA', 'Jira'), ('SERVICENOW', 'ServiceNow'), ('OTHER', 'Other ticketing platform')], default='NONE', max_length=15)),
                ('external_ticketing_enabled', models.BooleanField(default=False)),
                ('create_for_evidence', models.BooleanField(default=False)),
                ('create_for_findings', models.BooleanField(default=False)),
                ('create_for_remediation', models.BooleanField(default=False)),
                ('create_for_risk_treatment', models.BooleanField(default=False)),
                ('create_for_monitoring', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_policy', to='webapp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EVIDENCE', 'Evidence request'), ('FINDING', 'Finding'), ('REMEDIATION', 'Remediation action'), ('RISK', 'Risk treatment'), ('MONITORING', 'Monitoring or reassessment')], max_length=15)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('NONE', 'Not configured'), ('JIRA', 'Jira'), ('SERVICENOW', 'ServiceNow'), ('OTHER', 'Other ticketing platform')], default='NONE', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOT_CONFIGURED', 'Connector not configured'), ('QUEUED', 'Queued'), ('SYNCED', 'Synchronized'), ('FAILED', 'Failed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('external_ticket_id', models.CharField(blank=True, max_length=100)),
                ('external_ticket_url', models.URLField(blank=True, max_length=1000)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_work_items', to='webapp.assessment')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_work_items', to='webapp.membership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outbound_work_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_work_items', to='webapp.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='assessmenttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_assessment_template_per_org'),
        ),
        migrations.AddConstraint(
            model_name='outboundworkitem',
            constraint=models.UniqueConstraint(fields=('organization', 'event_type', 'object_type', 'object_id'), name='unique_outbound_work_item_source'),
        ),
    ]
