# Generated by Django 5.2.15 on 2026-08-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_sprint_19_templates_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceartifact',
            name='effective_on',
            field=models.DateField(blank=True, help_text='Date the evidence became effective or was issued.', null=True),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Allow Omni to create a renewal request before linked evidence expires.'),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='freshness_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Expected validity in days. Use 0 when this evidence does not expire.'),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='renewal_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='renewal_lead_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Open renewal work this many days before the evidence becomes stale.'),
        ),
        migrations.AddField(
            model_name='evidencerequest',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='webapp.evidencerequest'),
        ),
    ]
