# Generated by Django 5.2.15 on 2026-08-15 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_evidenceartifact_effective_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event_type', models.CharField(choices=[('SCHEDULED', 'Scheduled review'), ('EVIDENCE', 'Evidence freshness'), ('CHANGE', 'System or process change'), ('INCIDENT', 'Security or privacy incident'), ('VULNERABILITY', 'Vulnerability or threat'), ('AUDIT', 'Audit or assessment finding'), ('MANUAL', 'Manual observation')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=12)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField()),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('source_key', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_events', to='webapp.assessment')),
                ('controls', models.ManyToManyField(related_name='monitoring_events', to='webapp.controlassessment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_control_monitoring_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ControlMonitoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('review_frequency_days', models.PositiveSmallIntegerField(default=90)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('monitoring_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_profile', to='webapp.controlassessment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_monitoring_profiles', to='webapp.membership')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_control_monitoring_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_review_date', 'control_result__requirement__requirement_id'),
            },
        ),
        migrations.CreateModel(
            name='ControlReassessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('prior_conclusion', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Reassessed'), ('NO_ACTION', 'No action required')], default='OPEN', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_reassessment_tasks', to='webapp.membership')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_control_reassessment_tasks', to=settings.AUTH_USER_MODEL)),
                ('control_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessment_tasks', to='webapp.controlassessment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessment_tasks', to='webapp.controlmonitoringevent')),
            ],
            options={
                'ordering': ('status', 'due_date', 'control_result__requirement__requirement_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='controlmonitoringevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('assessment', 'source_key'), name='unique_monitoring_source_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='controlreassessmenttask',
            constraint=models.UniqueConstraint(fields=('event', 'control_result'), name='unique_reassessment_task_per_event_control'),
        ),
    ]
