"""Omni Evidence Body of Knowledge v1.0."""

from __future__ import annotations
from typing import Tuple

from src.evidence.evidence_object import (
    EvidenceObject,
    EvidenceCategory,
    EvidenceArtifactType,
)

VERSION = "1.0"


def _evidence(
    evidence_id: str,
    canonical_name: str,
    *,
    aliases: tuple[str, ...],
    category: EvidenceCategory,
    artifact_type: EvidenceArtifactType,
    description: str,
) -> EvidenceObject:
    return EvidenceObject(
        evidence_id=evidence_id,
        canonical_name=canonical_name,
        aliases=aliases,
        category=category,
        artifact_type=artifact_type,
        description=description,
    )


# Chunk 1: governance, planning, risk, and assurance.
EVIDENCE_KNOWLEDGE: Tuple[EvidenceObject, ...] = (
    _evidence(
        "EV-0001",
        "Security Plan",
        aliases=("System Security Plan", "SSP", "Information Security Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents the organization's security strategy and implementation.",
    ),
    _evidence(
        "EV-0002",
        "Security Policy",
        aliases=("Information Security Policy",),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines management direction and security requirements.",
    ),
    _evidence(
        "EV-0003",
        "Security Standards",
        aliases=("Technical Standards",),
        category=EvidenceCategory.STANDARD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines mandatory technical and organizational requirements.",
    ),
    _evidence(
        "EV-0004",
        "Security Procedures",
        aliases=("Operating Procedures",),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable operational security activities.",
    ),
    _evidence(
        "EV-0005",
        "Risk Assessment",
        aliases=("Risk Analysis", "Risk Assessment Report"),
        category=EvidenceCategory.ASSESSMENT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Evaluates threats, vulnerabilities, likelihood and impact.",
    ),
    _evidence(
        "EV-0006",
        "Risk Register",
        aliases=("Enterprise Risk Register",),
        category=EvidenceCategory.REGISTER,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Tracks identified risks and their disposition.",
    ),
    _evidence(
        "EV-0007",
        "Remediation Action Plan",
        aliases=("POA&M", "POAM", "Corrective Action Plan", "Remediation Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Tracks corrective actions for identified deficiencies.",
    ),
    _evidence(
        "EV-0008",
        "Security Assessment",
        aliases=("Security Assessment Report", "Assessment Results"),
        category=EvidenceCategory.ASSESSMENT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents evaluation of implemented safeguards.",
    ),
    _evidence(
        "EV-0009",
        "Exception Register",
        aliases=("Policy Exception Register", "Risk Acceptance Register"),
        category=EvidenceCategory.REGISTER,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Tracks approved policy and control exceptions.",
    ),
    _evidence(
        "EV-0010",
        "Control Inventory",
        aliases=("Security Control Inventory", "Safeguard Inventory"),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of implemented security controls.",
    ),
    # Identity and Access.
    _evidence(
        "EV-0011",
        "Account Inventory",
        aliases=(
            "User Account List",
            "Account List",
            "System Account Inventory",
            "List of System Accounts",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of organizational user and system accounts.",
    ),
    _evidence(
        "EV-0012",
        "Privileged Account Inventory",
        aliases=(
            "Privileged Account List",
            "Administrative Account Inventory",
            "Admin Account List",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of accounts assigned elevated or administrative privileges.",
    ),
    _evidence(
        "EV-0013",
        "Access Authorization Records",
        aliases=(
            "Access Approval Records",
            "User Access Authorization Records",
            "Access Authorization Forms",
            "Access Authorizations",
            "Authorization Records",
            "Logical Access Approvals",
            "System Access Authorizations",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records approvals for granting or changing access privileges.",
    ),
    _evidence(
        "EV-0014",
        "Access Review Records",
        aliases=(
            "User Access Review Records",
            "Access Recertification Records",
            "Access Certification Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records periodic reviews and recertification of access privileges.",
    ),
    _evidence(
        "EV-0015",
        "Authentication Configuration",
        aliases=(
            "Authentication Settings",
            "Authentication System Configuration",
            "Login Configuration",
            "Password Configurations and Associated Documentation",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration governing how identities are authenticated.",
    ),
    _evidence(
        "EV-0016",
        "Credential Policy",
        aliases=(
            "Password Policy",
            "Credential Management Policy",
            "Authentication Credential Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for credentials throughout their lifecycle.",
    ),
    _evidence(
        "EV-0017",
        "Authenticator Management Procedures",
        aliases=(
            "Authenticator Procedures",
            "Credential Management Procedures",
            "Password Management Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents issuance, protection, replacement, and revocation of authenticators.",
    ),
    _evidence(
        "EV-0018",
        "Multi-Factor Authentication Configuration",
        aliases=(
            "MFA Configuration",
            "Two-Factor Authentication Configuration",
            "2FA Configuration",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration enforcing the use of multiple authentication factors.",
    ),
    _evidence(
        "EV-0019",
        "Remote Access Configuration",
        aliases=(
            "Remote Access Settings",
            "Remote Connectivity Configuration",
            "VPN Configuration",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration controlling and protecting remote system access.",
    ),
    _evidence(
        "EV-0020",
        "Identity Provider Configuration",
        aliases=(
            "IdP Configuration",
            "Identity Management System Configuration",
            "Directory Service Configuration",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration of the service that establishes and manages identities.",
    ),
    # Asset Management.
    _evidence(
        "EV-0021",
        "Hardware Asset Inventory",
        aliases=(
            "Hardware Inventory",
            "Device Inventory",
            "System Component Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of physical technology assets and system components.",
    ),
    _evidence(
        "EV-0022",
        "Software Asset Inventory",
        aliases=(
            "Software Inventory",
            "Application Inventory",
            "Installed Software Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of software, applications, and installed components.",
    ),
    _evidence(
        "EV-0023",
        "Information Asset Inventory",
        aliases=("Data Asset Inventory", "Information Inventory", "Data Inventory"),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of organizational information and data assets.",
    ),
    _evidence(
        "EV-0024",
        "Asset Ownership Records",
        aliases=("Asset Assignment Records", "Asset Custodian Records"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records responsibility and custodianship for organizational assets.",
    ),
    _evidence(
        "EV-0025",
        "Asset Lifecycle Records",
        aliases=(
            "Asset Acquisition Records",
            "Asset Transfer Records",
            "Asset Disposal Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records acquisition, assignment, transfer, and disposal of assets.",
    ),
    # Configuration Management.
    _evidence(
        "EV-0026",
        "Configuration Baseline",
        aliases=(
            "System Configuration Baseline",
            "Approved Configuration Baseline",
            "System Baseline Configuration",
        ),
        category=EvidenceCategory.BASELINE,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Defines the approved configuration state for a system or component.",
    ),
    _evidence(
        "EV-0027",
        "Secure Configuration Standard",
        aliases=(
            "Hardening Standard",
            "Security Configuration Standard",
            "Build Standard",
        ),
        category=EvidenceCategory.STANDARD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for securely configuring systems and components.",
    ),
    _evidence(
        "EV-0028",
        "System Configuration Export",
        aliases=(
            "Configuration Export",
            "System Settings Export",
            "Configuration Snapshot",
        ),
        category=EvidenceCategory.EXPORT,
        artifact_type=EvidenceArtifactType.DATABASE_EXPORT,
        description="Captures the actual configuration state of a system or component.",
    ),
    _evidence(
        "EV-0029",
        "Change Management Records",
        aliases=("Change Records", "Change Tickets", "Change Control Records"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records authorization, testing, implementation, and review of changes.",
    ),
    _evidence(
        "EV-0030",
        "Configuration Review Records",
        aliases=("Configuration Audit Records", "Baseline Review Records"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records reviews of configurations against approved baselines and standards.",
    ),
    # Network and System Architecture.
    _evidence(
        "EV-0031",
        "Network Diagram",
        aliases=("Network Architecture Diagram", "Network Topology Diagram"),
        category=EvidenceCategory.DIAGRAM,
        artifact_type=EvidenceArtifactType.DIAGRAM,
        description="Depicts network boundaries, components, connections, and trust zones.",
    ),
    _evidence(
        "EV-0032",
        "Data Flow Diagram",
        aliases=("Information Flow Diagram", "Data Movement Diagram"),
        category=EvidenceCategory.DIAGRAM,
        artifact_type=EvidenceArtifactType.DIAGRAM,
        description="Depicts how information moves between processes, systems, and boundaries.",
    ),
    _evidence(
        "EV-0033",
        "System Architecture Documentation",
        aliases=(
            "System Design Documentation",
            "System Architecture",
            "Security Architecture Document",
            "Enterprise Architecture Documentation",
            "Enterprise Security Architecture Documentation",
        ),
        category=EvidenceCategory.DIAGRAM,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Describes system components, interfaces, boundaries, and design.",
    ),
    _evidence(
        "EV-0034",
        "Network Device Configuration",
        aliases=(
            "Router Configuration",
            "Switch Configuration",
            "Network Equipment Configuration",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration of devices that route, switch, or control network traffic.",
    ),
    _evidence(
        "EV-0035",
        "Firewall Configuration",
        aliases=(
            "Firewall Rules",
            "Firewall Rule Set",
            "Firewall Configuration Export",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration enforcing network traffic restrictions and boundary protections.",
    ),
    # Logging and Monitoring.
    _evidence(
        "EV-0036",
        "Audit Logs",
        aliases=(
            "Audit Records",
            "Security Audit Logs",
            "System Logs",
            "Event Logs",
            "System Audit Logs and Records",
            "System Audit Logs and Records Across Different Repositories",
        ),
        category=EvidenceCategory.LOG,
        artifact_type=EvidenceArtifactType.LOG,
        description="Records security-relevant system, application, and user activity.",
    ),
    _evidence(
        "EV-0037",
        "Logging Configuration",
        aliases=(
            "Audit Configuration",
            "Log Collection Configuration",
            "Audit Settings",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration defining which events are recorded and collected.",
    ),
    _evidence(
        "EV-0038",
        "Log Review Records",
        aliases=(
            "Audit Log Review Records",
            "Log Review Reports",
            "Log Review Tickets",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records completed reviews and analysis of collected logs.",
    ),
    _evidence(
        "EV-0039",
        "Security Monitoring Configuration",
        aliases=("Monitoring Rules", "Detection Rules", "SIEM Configuration"),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration defining security monitoring and detection behavior.",
    ),
    _evidence(
        "EV-0040",
        "Security Alerts",
        aliases=(
            "Monitoring Alerts",
            "SIEM Alerts",
            "Detection Alerts",
            "Records of Security Alerts and Advisories",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records notifications generated by security monitoring and detection systems.",
    ),
    # Incident Response.
    _evidence(
        "EV-0041",
        "Incident Response Plan",
        aliases=(
            "Cybersecurity Incident Response Plan",
            "IR Plan",
            "Incident Management Plan",
        ),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines roles, responsibilities, and the coordinated approach for responding to incidents.",
    ),
    _evidence(
        "EV-0042",
        "Incident Response Procedures",
        aliases=(
            "Incident Handling Procedures",
            "Incident Management Procedures",
            "IR Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for detecting, analyzing, containing, and resolving incidents.",
    ),
    _evidence(
        "EV-0043",
        "Incident Records",
        aliases=(
            "Security Incident Records",
            "Incident Reports",
            "Incident Tickets",
            "Incident Case Records",
            "Incident Reporting Records and Documentation",
            "Incident Response Records and Documentation",
            "System Incident Reports",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records detected incidents, investigative findings, response actions, and outcomes.",
    ),
    _evidence(
        "EV-0044",
        "Incident Response Exercise Records",
        aliases=(
            "Incident Response Test Records",
            "Tabletop Exercise Results",
            "IR Exercise Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records exercises and tests used to validate incident response capabilities.",
    ),
    _evidence(
        "EV-0045",
        "Incident Communication Records",
        aliases=(
            "Incident Notification Records",
            "Breach Notification Records",
            "Incident Escalation Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records internal and external communications, escalation, and notifications related to incidents.",
    ),
    # Recovery and Continuity.
    _evidence(
        "EV-0046",
        "Business Continuity Plan",
        aliases=("BCP", "Continuity Plan", "Business Resilience Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines how critical business activities continue during disruptive events.",
    ),
    _evidence(
        "EV-0047",
        "Disaster Recovery Plan",
        aliases=("DRP", "IT Disaster Recovery Plan", "System Recovery Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines how technology services and information are restored after disruption.",
    ),
    _evidence(
        "EV-0048",
        "Backup Configuration",
        aliases=("Backup Settings", "Backup Schedule", "Backup System Configuration"),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration defining what information is backed up, how often, and where it is retained.",
    ),
    _evidence(
        "EV-0049",
        "Backup Records",
        aliases=(
            "Backup Logs",
            "Backup Job Records",
            "Backup Reports",
            "System Backup Logs or Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records completed, failed, and verified backup activities.",
    ),
    _evidence(
        "EV-0050",
        "Recovery Test Records",
        aliases=(
            "Restore Test Records",
            "Disaster Recovery Test Results",
            "Recovery Exercise Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records tests demonstrating that systems and information can be restored.",
    ),
    # Physical Security.
    _evidence(
        "EV-0051",
        "Physical Security Plan",
        aliases=("Facility Security Plan", "Physical Protection Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines physical protection measures for facilities, systems, and organizational assets.",
    ),
    _evidence(
        "EV-0052",
        "Physical Access Authorization Records",
        aliases=(
            "Facility Access Authorization Records",
            "Badge Access Approvals",
            "Physical Access Approvals",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records authorization to enter facilities and physically controlled areas.",
    ),
    _evidence(
        "EV-0053",
        "Physical Access Logs",
        aliases=(
            "Facility Access Logs",
            "Badge Access Logs",
            "Entry and Exit Logs",
            "Physical Access Control Logs or Records",
            "Physical Access Logs or Records",
        ),
        category=EvidenceCategory.LOG,
        artifact_type=EvidenceArtifactType.LOG,
        description="Records entry to and exit from facilities and physically controlled areas.",
    ),
    _evidence(
        "EV-0054",
        "Visitor Records",
        aliases=("Visitor Logs", "Visitor Access Records", "Guest Access Logs"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records visitor authorization, entry, escort, and departure information.",
    ),
    _evidence(
        "EV-0055",
        "Physical Security Monitoring Records",
        aliases=(
            "Physical Surveillance Records",
            "Facility Monitoring Records",
            "Physical Security Alarm Records",
            "Physical Access Monitoring Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records monitoring and detection activities protecting facilities and physical assets.",
    ),
    # Personnel Security.
    _evidence(
        "EV-0056",
        "Personnel Screening Records",
        aliases=(
            "Background Screening Records",
            "Background Check Records",
            "Personnel Vetting Records",
            "Records of Screened Personnel",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records screening and vetting performed before or during personnel engagement.",
    ),
    _evidence(
        "EV-0057",
        "Personnel Security Agreements",
        aliases=("Confidentiality Agreements", "Non-Disclosure Agreements"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents personnel acknowledgment of security, confidentiality, and acceptable-use obligations.",
    ),
    _evidence(
        "EV-0058",
        "Personnel Transfer Records",
        aliases=(
            "Employee Transfer Records",
            "Role Change Records",
            "Personnel Reassignment Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records security-relevant actions resulting from personnel transfers or role changes.",
    ),
    _evidence(
        "EV-0059",
        "Personnel Termination Records",
        aliases=(
            "Employee Termination Records",
            "Offboarding Records",
            "Separation Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records security-relevant actions completed when personnel leave the organization.",
    ),
    _evidence(
        "EV-0060",
        "Security Training Records",
        aliases=(
            "Security Awareness Training Records",
            "Role-Based Security Training Records",
            "Training Completion Records",
            "Training Records",
        ),
        category=EvidenceCategory.TRAINING,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records completion of security awareness and role-based security training.",
    ),
    # Third-Party Risk Management (TPRM).
    _evidence(
        "EV-0061",
        "Third-Party Inventory",
        aliases=(
            "Vendor Inventory",
            "Supplier Inventory",
            "Service Provider Inventory",
            "Third-Party Register",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of external parties that provide products, services, or access to organizational assets.",
    ),
    _evidence(
        "EV-0062",
        "Third-Party Risk Assessment",
        aliases=(
            "Vendor Risk Assessment",
            "Supplier Risk Assessment",
            "Third-Party Security Assessment",
        ),
        category=EvidenceCategory.ASSESSMENT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Evaluates risks arising from a third-party relationship or service.",
    ),
    _evidence(
        "EV-0063",
        "Third-Party Due Diligence Records",
        aliases=(
            "Vendor Due Diligence Records",
            "Supplier Due Diligence Records",
            "Third-Party Security Questionnaire",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records due diligence performed before establishing or renewing third-party relationships.",
    ),
    _evidence(
        "EV-0064",
        "Third-Party Agreements",
        aliases=(
            "Vendor Agreements",
            "Supplier Agreements",
            "Service Provider Agreements",
            "Third-Party Contracts",
            "Service Provider Contracts",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents contractual obligations between the organization and external parties.",
    ),
    _evidence(
        "EV-0065",
        "Third-Party Security Requirements",
        aliases=(
            "Vendor Security Requirements",
            "Supplier Security Requirements",
            "Third-Party Security Clauses",
        ),
        category=EvidenceCategory.STANDARD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines security and assurance requirements applicable to external parties.",
    ),
    _evidence(
        "EV-0066",
        "Third-Party Monitoring Records",
        aliases=(
            "Vendor Monitoring Records",
            "Supplier Monitoring Records",
            "Third-Party Oversight Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records ongoing monitoring of third-party risk, security, and compliance obligations.",
    ),
    _evidence(
        "EV-0067",
        "Third-Party Review Records",
        aliases=(
            "Vendor Review Records",
            "Supplier Review Records",
            "Service Provider Review Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records periodic reviews and decisions concerning third-party relationships.",
    ),
    # Cryptography.
    _evidence(
        "EV-0068",
        "Cryptographic Policy",
        aliases=(
            "Encryption Policy",
            "Cryptography Policy",
            "Cryptographic Controls Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements for using and protecting cryptographic mechanisms.",
    ),
    _evidence(
        "EV-0069",
        "Cryptographic Standards",
        aliases=(
            "Encryption Standards",
            "Cryptography Standards",
            "Approved Cryptographic Standards",
        ),
        category=EvidenceCategory.STANDARD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines approved algorithms, protocols, strengths, and cryptographic implementation requirements.",
    ),
    _evidence(
        "EV-0070",
        "Cryptographic Asset Inventory",
        aliases=(
            "Cryptography Inventory",
            "Encryption Inventory",
            "Cryptographic Mechanism Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of cryptographic mechanisms and their organizational use.",
    ),
    _evidence(
        "EV-0071",
        "Key Management Procedures",
        aliases=(
            "Cryptographic Key Management Procedures",
            "Encryption Key Procedures",
            "Key Lifecycle Procedures",
            "Cryptographic Key Establishment and Management Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents generation, distribution, storage, rotation, recovery, and destruction of cryptographic keys.",
    ),
    _evidence(
        "EV-0072",
        "Key Management Records",
        aliases=(
            "Cryptographic Key Records",
            "Key Rotation Records",
            "Key Lifecycle Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records cryptographic key lifecycle events and authorized management activities.",
    ),
    _evidence(
        "EV-0073",
        "Cryptographic Configuration",
        aliases=(
            "Encryption Configuration",
            "Cryptography Configuration",
            "Cryptographic Settings",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration demonstrating how cryptographic protections are implemented.",
    ),
    _evidence(
        "EV-0074",
        "Certificate Inventory",
        aliases=(
            "Digital Certificate Inventory",
            "TLS Certificate Inventory",
            "PKI Certificate Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of digital certificates, their purpose, ownership, and lifecycle status.",
    ),
    # Security Operations.
    _evidence(
        "EV-0075",
        "Security Operations Procedures",
        aliases=(
            "SecOps Procedures",
            "Security Operations Center Procedures",
            "SOC Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities performed to operate and protect systems securely.",
    ),
    _evidence(
        "EV-0076",
        "Vulnerability Scan Report",
        aliases=(
            "Vulnerability Scan Results",
            "Vulnerability Assessment Report",
            "Technical Vulnerability Report",
            "Vulnerability Scanning Results",
        ),
        category=EvidenceCategory.REPORT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Reports technical vulnerabilities identified through scanning or assessment.",
    ),
    _evidence(
        "EV-0077",
        "Vulnerability Management Records",
        aliases=(
            "Vulnerability Tracking Records",
            "Vulnerability Remediation Records",
            "Vulnerability Tickets",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records evaluation, prioritization, assignment, remediation, and closure of vulnerabilities.",
    ),
    _evidence(
        "EV-0078",
        "Patch Management Records",
        aliases=(
            "Patch Records",
            "Patch Deployment Records",
            "Security Update Records",
            "List of Recent Security Flaw Remediation Actions Performed on the System E G List of Installed Patches Service Packs Hot Fixes and Other Software Updates to Correct System Flaws",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records evaluation, approval, deployment, and verification of patches and security updates.",
    ),
    _evidence(
        "EV-0079",
        "Malware Protection Configuration",
        aliases=(
            "Anti-Malware Configuration",
            "Antivirus Configuration",
            "Endpoint Protection Configuration",
            "Malicious Code Protection Mechanisms",
        ),
        category=EvidenceCategory.CONFIGURATION,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Configuration demonstrating how malicious code prevention and detection are implemented.",
    ),
    _evidence(
        "EV-0080",
        "Security Operations Reports",
        aliases=(
            "SecOps Reports",
            "Security Operations Center Reports",
            "Security Operations Metrics",
        ),
        category=EvidenceCategory.REPORT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Reports operational security activities, performance, trends, and outcomes.",
    ),
    # Access Control and Identity Operations.
    _evidence(
        "EV-0081",
        "Access Control Policy",
        aliases=("Logical Access Control Policy",),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for authorizing, enforcing, reviewing, and revoking logical access.",
    ),
    _evidence(
        "EV-0082",
        "Access Control Procedures",
        aliases=("Logical Access Control Procedures",),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for administering and enforcing logical access.",
    ),
    _evidence(
        "EV-0083",
        "Access Control List",
        aliases=(
            "ACL",
            "Access Control Rules",
            "Access Permissions List",
            "Service Account Permissions",
        ),
        category=EvidenceCategory.LIST,
        artifact_type=EvidenceArtifactType.CONFIGURATION,
        description="Lists permissions or rules that govern access to a resource.",
    ),
    _evidence(
        "EV-0084",
        "Account Management Procedures",
        aliases=(
            "Account Administration Procedures",
            "User Account Management Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents account creation, modification, review, disablement, and removal activities.",
    ),
    _evidence(
        "EV-0085",
        "Credential Inventory",
        aliases=(
            "Access Credential Inventory",
            "Authenticator Inventory",
            "Credential Register",
            "Access Credentials",
            "Authorization Credentials",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of credentials and authenticators issued or managed by the organization.",
    ),
    _evidence(
        "EV-0086",
        "Authorized Personnel List",
        aliases=("List of Authorized Personnel", "Authorized Personnel Access List"),
        category=EvidenceCategory.LIST,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Identifies personnel authorized for specified systems, facilities, or responsibilities.",
    ),
    # Configuration Management Governance.
    _evidence(
        "EV-0087",
        "Configuration Management Plan",
        aliases=("CM Plan", "Configuration Control Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines the organizational approach, responsibilities, and resources for configuration management.",
    ),
    _evidence(
        "EV-0088",
        "Configuration Management Policy",
        aliases=("Configuration Control Policy", "CM Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements for managing and controlling configurations.",
    ),
    _evidence(
        "EV-0089",
        "Configuration Management Procedures",
        aliases=("Configuration Control Procedures", "CM Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable configuration and change-control activities.",
    ),
    _evidence(
        "EV-0090",
        "Security Impact Analysis",
        aliases=(
            "Security Impact Analysis Documentation",
            "Change Security Impact Analysis",
        ),
        category=EvidenceCategory.ASSESSMENT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Evaluates the security effects of proposed or implemented changes.",
    ),
    # Media Protection.
    _evidence(
        "EV-0091",
        "Media Protection Policy",
        aliases=(
            "System Media Protection Policy",
            "Information Media Protection Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for protecting physical and digital information media.",
    ),
    _evidence(
        "EV-0092",
        "Media Protection Procedures",
        aliases=("System Media Protection Procedures", "Media Handling Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for accessing, marking, storing, transporting, and sanitizing media.",
    ),
    _evidence(
        "EV-0093",
        "Media Inventory",
        aliases=(
            "System Media Inventory",
            "Removable Media Inventory",
            "Media Register",
            "System Media",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of physical and digital media containing organizational information.",
    ),
    _evidence(
        "EV-0094",
        "Media Sanitization Records",
        aliases=(
            "Media Disposal Records",
            "Media Destruction Records",
            "Equipment Sanitization Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records sanitization, destruction, or disposal of media and information-bearing equipment.",
    ),
    _evidence(
        "EV-0095",
        "Media Transport Records",
        aliases=(
            "System Media Transport Records",
            "Media Transfer Records",
            "Media Chain of Custody Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records authorization, custody, and movement of media outside controlled areas.",
    ),
    # System Maintenance.
    _evidence(
        "EV-0096",
        "Maintenance Policy",
        aliases=("System Maintenance Policy", "Technology Maintenance Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for authorized and controlled system maintenance.",
    ),
    _evidence(
        "EV-0097",
        "Maintenance Procedures",
        aliases=("System Maintenance Procedures", "Equipment Maintenance Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for performing and controlling maintenance.",
    ),
    _evidence(
        "EV-0098",
        "Maintenance Records",
        aliases=(
            "System Maintenance Records",
            "Equipment Maintenance Records",
            "Maintenance Logs",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records authorized maintenance activities, personnel, tools, and outcomes.",
    ),
    _evidence(
        "EV-0099",
        "Maintenance Tool Inventory",
        aliases=(
            "System Maintenance Tool Inventory",
            "Maintenance Equipment Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of tools and equipment approved for system maintenance.",
    ),
    _evidence(
        "EV-0100",
        "Maintenance Tool Inspection Records",
        aliases=("Maintenance Equipment Inspection Records",),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records inspections and controls applied to maintenance tools and equipment.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 1.
    _evidence(
        "EV-0101",
        "Mobile Device Access Procedures",
        aliases=(
            "Access Control for Mobile Device Usage Including Restrictions Procedures",
            "Access Control for Mobile Devices Procedures",
            "Mobile Device Security Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents access controls and usage restrictions for mobile devices.",
    ),
    _evidence(
        "EV-0102",
        "Account Management Review Records",
        aliases=("Account Management Compliance Reviews", "Account Review Records"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records reviews of account management activities and compliance with account requirements.",
    ),
    _evidence(
        "EV-0103",
        "Configuration Change Control Meeting Records",
        aliases=(
            "Agenda Minutes from Configuration Change Control Oversight Meetings",
            "Change Control Board Meeting Records",
            "Configuration Control Board Minutes",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records oversight meetings and decisions concerning configuration changes.",
    ),
    _evidence(
        "EV-0104",
        "Alternate Work Site Security Procedures",
        aliases=(
            "Alternate Work Sites for Personnel Procedures",
            "Alternate Worksite Security Procedures",
            "Remote Work Site Security Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents safeguards and responsibilities for work performed at alternate locations.",
    ),
    _evidence(
        "EV-0105",
        "Security Analysis Tool Inventory",
        aliases=("Security Analysis Tools", "Analysis Tool Inventory"),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of tools used to analyze security events, records, configurations, or system behavior.",
    ),
    _evidence(
        "EV-0106",
        "Security Analysis Results",
        aliases=("Security Analysis Outputs", "Security Analysis Findings"),
        category=EvidenceCategory.REPORT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Records outputs and findings produced through security analysis activities.",
    ),
    _evidence(
        "EV-0107",
        "Media Handling and Sanitization Policy",
        aliases=(
            "Applicable Standards and Policies Addressing Media Sanitization",
            "Media Sanitization Policy",
            "Media Handling Policy",
            "Media Disposal Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for handling, sanitizing, destroying, and disposing of information media.",
    ),
    _evidence(
        "EV-0108",
        "Application Segmentation and Isolation Procedures",
        aliases=(
            "Application Partitioning Procedures",
            "Application Segmentation Procedures",
            "Data Isolation Procedures",
            "Application Compartmentalization Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents architectural separation and isolation of application functions, data, and shared resources.",
    ),
    _evidence(
        "EV-0109",
        "Alternate Work Site Security Assessment",
        aliases=(
            "Assessments of Safeguards at Alternate Work Sites",
            "Alternate Worksite Security Assessment",
            "Remote Work Site Security Assessment",
        ),
        category=EvidenceCategory.ASSESSMENT,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Evaluates safeguards implemented at alternate or remote work locations.",
    ),
    _evidence(
        "EV-0110",
        "Audit and Accountability Policy",
        aliases=("Audit Policy", "Audit Logging Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for event logging, audit records, accountability, review, and protection.",
    ),
    _evidence(
        "EV-0111",
        "Audit Logging Tool Inventory",
        aliases=(
            "Audit Logging Tools",
            "Audit Tool Inventory",
            "Logging Tool Inventory",
        ),
        category=EvidenceCategory.INVENTORY,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Inventory of tools used to generate, collect, protect, analyze, or report audit records.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 2.
    _evidence(
        "EV-0112",
        "Audit Logging Procedures",
        aliases=(
            "Audit Record Reduction and Report Generation Procedures",
            "Audit Record Review Analysis and Reporting Procedures",
            "Audit Records and Event Types Procedures",
            "Auditable Events Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents event selection, log retention, review, analysis, reduction, escalation, and reporting activities.",
    ),
    _evidence(
        "EV-0113",
        "Boundary Protection Procedures",
        aliases=(
            "Network Boundary Protection Procedures",
            "Perimeter Security Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for monitoring, controlling, and protecting system boundaries.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 3.
    _evidence(
        "EV-0114",
        "Contingency Plan",
        aliases=("System Contingency Plan", "Information System Contingency Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines contingency roles, priorities, resources, and response and recovery arrangements for disruptions.",
    ),
    _evidence(
        "EV-0115",
        "Contingency Plan Testing Procedures",
        aliases=("Contingency Plan Test Procedures", "Contingency Testing Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for exercising and validating contingency plans.",
    ),
    _evidence(
        "EV-0116",
        "Contingency Planning Policy",
        aliases=("Contingency Policy", "System Contingency Planning Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements for contingency planning, response, testing, and recovery.",
    ),
    _evidence(
        "EV-0117",
        "Continuous Monitoring Strategy",
        aliases=(
            "Information Security Continuous Monitoring Strategy",
            "ISCM Strategy",
        ),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines the organizational approach, scope, frequency, and responsibilities for continuous monitoring.",
    ),
    _evidence(
        "EV-0118",
        "Cryptographic Module Validation Certificates",
        aliases=("Cryptographic Validation Certificates", "FIPS Module Certificates"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents independent validation status for cryptographic modules and implementations.",
    ),
    _evidence(
        "EV-0119",
        "Cryptographic Protection Procedures",
        aliases=("Encryption Protection Procedures", "Cryptography Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for applying and maintaining cryptographic protections.",
    ),
    _evidence(
        "EV-0120",
        "Controlled Area Register",
        aliases=(
            "Designated Controlled Areas",
            "Controlled Area List",
            "Restricted Area Register",
        ),
        category=EvidenceCategory.REGISTER,
        artifact_type=EvidenceArtifactType.DATASET,
        description="Identifies facilities and spaces designated for controlled or restricted physical access.",
    ),
    _evidence(
        "EV-0121",
        "Diagnostic Records",
        aliases=(
            "System Diagnostic Records",
            "Diagnostic Test Records",
            "Troubleshooting Records",
        ),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.RECORD,
        description="Records diagnostic activities, results, and actions performed on systems or components.",
    ),
    _evidence(
        "EV-0122",
        "Separation of Duties Procedures",
        aliases=(
            "Divisions of Responsibility and Separation of Duties Procedures",
            "Segregation of Duties Procedures",
            "SoD Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents how incompatible responsibilities and privileges are divided among personnel or roles.",
    ),
    _evidence(
        "EV-0123",
        "System Use Banner Policy",
        aliases=(
            "System Use Notification Policy",
            "Login Banner Policy",
            "System Use Notification and Banner Policy",
            "Documented Approval of System Use Notification Messages or Banners",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines approved system-use notification and login-banner requirements and language.",
    ),
    _evidence(
        "EV-0124",
        "Facility Diagram",
        aliases=(
            "Facility Diagram Layout",
            "Facility Diagram or Layout",
            "Facility Layout",
        ),
        category=EvidenceCategory.DIAGRAM,
        artifact_type=EvidenceArtifactType.DIAGRAM,
        description="Depicts facility spaces, boundaries, controlled areas, entrances, and relevant physical protections.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 4.
    _evidence(
        "EV-0125",
        "Vulnerability Remediation Procedures",
        aliases=("Flaw Remediation Procedures", "Security Flaw Remediation Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for evaluating, prioritizing, correcting, and verifying vulnerabilities and security flaws.",
    ),
    _evidence(
        "EV-0126",
        "Identity and Access Management Policy",
        aliases=("Identification and Authentication Policy", "IAM Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for identity, account, credential, authentication, and access management.",
    ),
    _evidence(
        "EV-0127",
        "Identity and Access Management Procedures",
        aliases=("Identification and Authentication Procedures", "IAM Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable identity, account, credential, authentication, and access management activities.",
    ),
    _evidence(
        "EV-0128",
        "Incident Response Policy",
        aliases=(
            "Cybersecurity Incident Response Policy",
            "Incident Management Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements, responsibilities, and authority for incident response.",
    ),
    _evidence(
        "EV-0129",
        "Incident Response Exercise Plan",
        aliases=("Incident Response Test Plan", "IR Exercise Plan"),
        category=EvidenceCategory.PLAN,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines objectives, scenarios, participants, and activities for an incident response exercise.",
    ),
    _evidence(
        "EV-0130",
        "Incident Response Exercise Materials",
        aliases=("Incident Response Testing Material", "IR Exercise Materials"),
        category=EvidenceCategory.RECORD,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Contains scenarios, injects, scripts, and supporting content used during incident response exercises.",
    ),
    _evidence(
        "EV-0131",
        "Incident Response Exercise Procedures",
        aliases=("Incident Response Testing Procedures", "IR Exercise Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for planning, conducting, evaluating, and improving incident response exercises.",
    ),
    _evidence(
        "EV-0132",
        "Incident Response Training Materials",
        aliases=(
            "Incident Response Training Curriculum",
            "IR Training Curriculum",
        ),
        category=EvidenceCategory.TRAINING,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Contains curriculum and instructional content used to train personnel on incident response responsibilities.",
    ),
    _evidence(
        "EV-0133",
        "Incident Response Training Procedures",
        aliases=("IR Training Procedures", "Incident Response Training Process"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents how incident response training is assigned, delivered, tracked, reviewed, and updated.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 5.
    _evidence(
        "EV-0134",
        "Security Architecture Policy",
        aliases=(
            "Information Flow Control Policies",
            "Information Flow Security Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for security architecture, trust boundaries, segmentation, isolation, and information flow.",
    ),
    _evidence(
        "EV-0135",
        "Security Architecture Procedures",
        aliases=(
            "Information Flow Enforcement Procedures",
            "Architecture Enforcement Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for implementing and maintaining architectural security and information-flow controls.",
    ),
    _evidence(
        "EV-0136",
        "Insider Threat Policy",
        aliases=("Insider Risk Policy",),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements and responsibilities for managing insider threats and insider risk.",
    ),
    _evidence(
        "EV-0137",
        "Insider Threat Procedures",
        aliases=("Insider Risk Procedures", "Insider Threat Management Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for identifying, reporting, assessing, and responding to insider threats.",
    ),
    _evidence(
        "EV-0138",
        "Asset Management Policy",
        aliases=("Asset Inventory Policy", "Information Asset Management Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for identifying, owning, protecting, reviewing, and maintaining organizational assets.",
    ),
    _evidence(
        "EV-0139",
        "Asset Management Procedures",
        aliases=(
            "Asset Inventory Procedures",
            "Information Asset Management Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for inventorying, assigning, reviewing, updating, and disposing of assets.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 7.
    _evidence(
        "EV-0140",
        "Physical Security Policy",
        aliases=(
            "Physical and Environmental Protection Policy",
            "Physical and Environmental Security Policy",
        ),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements for protecting facilities, controlled areas, publicly accessible areas, personnel, and physical assets.",
    ),
    _evidence(
        "EV-0141",
        "Public Communications Procedures",
        aliases=(
            "Public Relations Procedures",
            "Publicly Accessible Content Procedures",
            "Public Content Publishing Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents authorization, approval, review, publication, correction, and removal of publicly accessible organizational content.",
    ),
    _evidence(
        "EV-0142",
        "Malware Protection Procedures",
        aliases=(
            "Malicious Code Protection Procedures",
            "Malicious Software Protection Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for preventing, detecting, analyzing, containing, and remediating malicious code.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 8.
    _evidence(
        "EV-0143",
        "Risk Assessment Procedures",
        aliases=(
            "Risk Analysis Procedures",
            "Organizational Risk Assessment Procedures",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for identifying, analyzing, evaluating, documenting, reviewing, and updating risk assessments.",
    ),
    _evidence(
        "EV-0144",
        "Human Resources Manual",
        aliases=("HR Manual", "Personnel Manual", "Employee Handbook"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines personnel lifecycle requirements, including screening, conduct, security responsibilities, transfers, and termination or offboarding.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 10.
    _evidence(
        "EV-0145",
        "Risk Management Policy",
        aliases=("Enterprise Risk Management Policy", "ERM Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines organizational requirements, responsibilities, criteria, and governance for identifying, assessing, treating, monitoring, and reporting risk.",
    ),
    _evidence(
        "EV-0146",
        "Acceptable Use Policy",
        aliases=("Rules of Behavior", "AUP", "Acceptable Use Rules"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines acceptable and prohibited use of organizational systems, information, devices, services, and other technology resources.",
    ),
    # Sprint 3.10 generated-evidence gap curation, Batch 11.
    _evidence(
        "EV-0147",
        "Security Assessment Procedures",
        aliases=("Security Assessments Procedures", "Assessment Procedures"),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents repeatable activities for planning, conducting, documenting, reviewing, and following up on security assessments.",
    ),
    _evidence(
        "EV-0148",
        "Security Awareness and Training Policy",
        aliases=("Security Training Policy", "Awareness and Training Policy"),
        category=EvidenceCategory.POLICY,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Defines requirements, responsibilities, scope, frequency, and oversight for security awareness and training.",
    ),
    _evidence(
        "EV-0149",
        "Security Awareness Training Procedures",
        aliases=(
            "Security Awareness Training Curriculum",
            "Security Awareness Training Implementation Procedures",
            "Security Awareness Training Materials",
        ),
        category=EvidenceCategory.PROCEDURE,
        artifact_type=EvidenceArtifactType.DOCUMENT,
        description="Documents how security awareness training is designed, delivered, maintained, reviewed, and supported by curriculum and training materials.",
    ),
)


def evidence_knowledge() -> Tuple[EvidenceObject, ...]:
    return EVIDENCE_KNOWLEDGE
